---

apiVersion: v1
kind: Namespace
metadata:
  name: comment
---
apiVersion: v1
kind: Service
metadata:
  name: comment-svc
  namespace: comment
spec:
  ports:
    - port: 19008
  selector:
    app: comment
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
  namespace: comment
spec:
  replicas: 1  # 副本数，根据需要调整
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
        - name: comment
          image: 10.1.182.202:443/vk-25/comment:${IMAGE_TAG}  # 使用适合的版本
          env:
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
          ports:
            - containerPort: 19008
          volumeMounts:
            - mountPath: /vk/prod/logs
              name: log-volume
      volumes:
        - name: log-volume
          hostPath:
            path: /mnt/data/logs/comment
            type: DirectoryOrCreate
