---

apiVersion: v1
kind: Namespace
metadata:
  name: user
---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: user
spec:
  ports:
    - port: 19003
  selector:
    app: user
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: user
spec:
  replicas: 1  # 副本数，根据需要调整
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: registry-svc.registry/vk-25/user:${IMAGE_TAG}  # 使用适合的版本
          env:
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
          ports:
            - containerPort: 19003
          volumeMounts:
            - mountPath: /vk/prod/logs
              name: log-volume
            - mountPath: /vk/prod/xxl-job
              name: job-log
      volumes:
        - name: log-volume
          hostPath:
            path: /mnt/data/logs/user
            type: DirectoryOrCreate
        - name: job-log
          hostPath:
            path: /mnt/data/logs/user/job
            type: DirectoryOrCreate