---

apiVersion: v1
kind: Namespace
metadata:
  name: ai
---
apiVersion: v1
kind: Service
metadata:
  name: ai-svc
  namespace: ai
spec:
  ports:
    - port: 19010
  selector:
    app: ai
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
  namespace: ai
spec:
  replicas: 1  # 副本数，根据需要调整
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
        - name: ai
          image: registry.cn-shenzhen.aliyuncs.com/vk-25/ai:${IMAGE_TAG}  # 使用适合的版本
          env:
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
          ports:
            - containerPort: 19010
          volumeMounts:
            - mountPath: /vk/prod/logs
              name: log-volume
      volumes:
        - name: log-volume
          hostPath:
            path: /mnt/data/logs/ai
            type: DirectoryOrCreate
