---

apiVersion: v1
kind: Namespace
metadata:
  name: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: gateway
spec:
  ports:
    - port: 16001
  selector:
    app: gateway
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: gateway
spec:
  replicas: 1  # 副本数，根据需要调整
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 10.1.182.202:443/vk-25/gateway:${IMAGE_TAG}  # 使用适合的版本
          env:
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
          ports:
            - containerPort: 16001
          volumeMounts:
            - mountPath: /vk/prod/logs
              name: log-volume
      volumes:
        - name: log-volume
          hostPath:
            path: /mnt/data/logs/gateway
            type: DirectoryOrCreate

---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: gateway-ingress
#  namespace: gateway
#  annotations:
#    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # 强制使用 HTTPS
#    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: "api.aidighub.com"  # 设置外部域名
#      http:
#        paths:
#          - path: /api(/|$)(.*)  # 匹配路径 /api 及其后续部分
#            pathType: ImplementationSpecific
#            backend:
#              service:
#                name: gateway-svc
#                port:
#                  number: 16001
#  tls:
#    - hosts:
#        - "api.aidighub.com"  # 设置 TLS 证书的域名
#      secretName: gateway-tls-secret  # 这里是你的 TLS 证书的 Secret 名称