---

apiVersion: v1
kind: Namespace
metadata:
  name: system
---
apiVersion: v1
kind: Service
metadata:
  name: system-svc
  namespace: system
spec:
  ports:
    - port: 19002
  selector:
    app: system
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system
  namespace: system
spec:
  replicas: 1  # 副本数，根据需要调整
  selector:
    matchLabels:
      app: system
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
        - name: system
          image: registry-svc.registry/vk-25/system:${IMAGE_TAG}  # 使用适合的版本
          env:
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
          ports:
            - containerPort: 19002
          volumeMounts:
            - mountPath: /vk/prod/logs
              name: log-volume
      volumes:
        - name: log-volume
          hostPath:
            path: /mnt/data/logs/system
            type: DirectoryOrCreate
