---

apiVersion: v1
kind: Namespace
metadata:
  name: media
---
apiVersion: v1
kind: Service
metadata:
  name: media-svc
  namespace: media
spec:
  ports:
    - port: 19005
  selector:
    app: media
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media
  namespace: media
spec:
  replicas: 1  # 副本数，根据需要调整
  selector:
    matchLabels:
      app: media
  template:
    metadata:
      labels:
        app: media
    spec:
      containers:
        - name: media
          image: registry-svc.registry/vk-25/wemedia:${IMAGE_TAG}  # 使用适合的版本
          env:
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
          ports:
            - containerPort: 19005
          volumeMounts:
            - mountPath: /vk/prod/logs
              name: log-volume
      volumes:
        - name: log-volume
          hostPath:
            path: /mnt/data/logs/media
            type: DirectoryOrCreate
