---
#Namespace dev
apiVersion: v1
kind: Namespace
metadata:
  name: search
---
apiVersion: v1
kind: Service
metadata:
  name: search-svc
  namespace: search
spec:
  ports:
    - port: 19009
  selector:
    app: search
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  namespace: search
spec:
  replicas: 1  # 副本数，根据需要调整
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: registry.cn-shenzhen.aliyuncs.com/vk-25/search:${IMAGE_TAG}  # 使用适合的版本
          env:
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
          ports:
            - containerPort: 19009
